# Generated by Django 5.2.6 on 2025-09-07 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nombre', models.IntegerField(default=1, max_length=2)),
                ('est_present', models.BooleanField(default=False)),
                ('attente_de_validation', models.BooleanField(default=False)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='cheking.qrcode')),
            ],
        ),
        migrations.AddField(
            model_name='qrcode',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheking.tables'),
        ),
    ]
