# Generated by Django 3.2.25 on 2025-09-08 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LienAmitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='invite',
            name='nombre',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheking.ville')),
            ],
        ),
        migrations.AddField(
            model_name='invite',
            name='lien_amitie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheking.lienamitie'),
        ),
        migrations.AddField(
            model_name='invite',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheking.quartier'),
        ),
        migrations.AddField(
            model_name='invite',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cheking.ville'),
        ),
    ]
